### PR TITLE
Fixed some bugs

### PR DESCRIPTION
**Pull request by xwang233**
Thank the author for this wonderful project. I wanted to used this repo as a front-end and I tried to add a C++ bot back-end for myself. I have learned a lot of javascript skills during the modifications, and fixed some bugs. 

For example, in the original version, when piece A can jump, player can move piece B and totally ignore the force jump of piece A. I added a member variable `jumpexist` for `board` to check if there is a force jump for `this.playerTurn`. When `jumpexist == true`, the branch `if(inRange=='regular')` won't execute, and player can not make a move in this situation. 

Also, I moved `changePlayerTurn()` function outside of the `Piece.move()`. Now, the `changePlayerTurn()` executes at the end of `tile.on(click)`. So there won't be player changes or change-back during the continuous jumps. The player change happens after all the possible continuous jumps.  At the end of `changePlayerTurn()`, `board.jumpexist` is checked using a function I provided.

### CODE REVIEW

**Comment by codethejason** [comment]
Thanks for the contributions, looks good! Do you have a link to a working demo of the website?

**Comment by xwang233** [comment]
I have hosted the bug-fix branch on my git pages at https://society765.github.io/checkers-visualize/. However, I just realized there is still a small bug. When there are continuous jumps for piece A, one can still jump piece A for one step, then jump piece B (but not regular move B). I think this can be done by adding restrictions to de-select piece A after one jump (if following jumps exist).

**Comment by codethejason** [comment]
Would you be able to add that bug fix into this PR?

**Comment by xwang233** [comment]
I have fixed the above mentioned issue. You may check a live demo at https://society765.github.io/checkers-visualize/. 

Specifically, I added `allowedtomove` member to Piece object. When jump exist, only those pieces can jump are `allowedtomove`; when jump doesn't exist, all pieces are `allowedtomove`. When click on a piece, if it is not `allowedtomove`, there will be no response (line 266). 

Also, I added `continuousjump` member to Board object. This is set to `true` when continuous jump exist (line 303). When `Board.continuousjump == true`, the piece-click function won't response either (line 266). Only the current active piece can perform a next continuous jump. 

I also added some `console.log` near line 272, the author may set them as alert or other status message to remind user of allowed moves.

**Comment by codethejason** [comment]
Thanks, close #1.

**Pull request merged**
